OUTPUT_DIR: "checkpoints"
LOG_FILE_NAME: "sun_train.log"
MODEL_FILE_NAME: "sun_train.pth"
MODEL:
  META_ARCHITECTURE: "Model"
  SCALE: 25.0
  BACKBONE:
    PRETRAINED: True
  ATTENTION:
    CHANNEL: 512
    WEIGHT_SHARED: True
    # W2V_PATH: "../datasets/Attribute/w2v"
    W2V_PATH: "w2v"
  LOSS:
    LAMBDA1: 1.0
    LAMBDA2: 0.5
    LAMBDA3: 0.02
    LAMBDA4: 0.2

DATASETS:
  NAME: "SUN"
  IMAGE_SIZE: 224
  WAYS: 16
  SHOTS: 3

DATALOADER:
  MODE: 'episode'
  N_BATCH: 300

SOLVER:
  MAX_EPOCH: 25 
  BASE_LR: 1e-3
  # BASE_LR: 1e-4
  WEIGHT_DECAY: 1e-4
  MOMENTUM: 0.9
  GAMMA: 0.1
  STEPS: 5
  DATA_AUG: "resize_random_crop"

TEST:
  IMS_PER_BATCH: 100
  DATA_AUG: "resize_crop"
  # DATA_AUG: "resize_random_crop"
  GAMMA: 1.5
